### ISSUE TITLE
 Ошибка при обновлении аккаунта: TypeError: Cannot read properties of undefined (reading 'opponent')

### ISSUE THREAD

**Issue by Domenick90** [Newmcpe/fuflomuskempire#6]
[HEARTBEAT] Domenick | Ошибка при обновлении аккаунта: TypeError: Cannot read properties of undefined (reading 'opponent')
    at Object.combater (file:///home/osboxes/fuflomuskempire/dist/modules/combater.js:19:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Timeout.accountHeartbeat [as _onTimeout] 

[HEARTBEAT] Domenick | Ошибка при обновлении аккаунта: TypeError: Cannot read properties of undefined (reading 'opponent')
    at Object.combater (file:///home/osboxes/fuflomuskempire/dist/modules/combater.js:19:29)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Timeout.accountHeartbeat [as _onTimeout] (file:///home/osboxes/fuflomuskempire/dist/modules/heartbeat.js:24:13)

**Comment by Newmcpe** [comment]
странное поведение, сделала null-safety в коммите
