### ISSUE TITLE
Проблема запуска на Linux

### ISSUE THREAD

**Issue by asafov** [Newmcpe/fuflomuskempire#9]
```
asafov@asafov:~/bots/fuflomuskempire$ pnpm install
Lockfile is up to date, resolution step is skipped
Already up to date

> fuflomaskempire@0.0.0 prepare /home/asafov/bots/fuflomuskempire
> husky || true

file:///home/asafov/bots/fuflomuskempire/node_modules/.pnpm/husky@9.0.11/node_modules/husky/bin.mjs:14
	;(o.scripts ||= {}).prepare = 'husky'
	              ^

SyntaxError: Unexpected token '='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

```
```
node --version
v12.22.9
```
Соответственно и докерную версию я запустить не могу, так как не могу запуститься без докера.

**Comment by Newmcpe** [comment]
Бот поддерживает минимум 20 версию Node

**Comment by asafov** [comment]
Понял, это то, что по умолчанию в репе. Доставлю тогда до нужной и попробую еще. Спасибо.
